//! On-disk plugin load order: the Proton-prefix path resolver plus reading and
//! writing `plugins.txt` / `loadorder.txt` in the formats the games expect.
//!
//! These files do NOT live in the Data dir Eidos mounts over - they live in the
//! game's local AppData inside the Proton prefix:
//!   `<prefix>/drive_c/users/steamuser/AppData/Local/<game>/`
//! Eidos writes them there right before launch. The format here was verified
//! against a real MO2-generated Skyrim SE load order.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::{GameSpec, LoadOrderMechanism, PluginList};

const HEADER: &str = "# This file was automatically generated by Eidos.";

/// The directory holding `plugins.txt` / `loadorder.txt` inside a Proton prefix.
/// `prefix` is the `pfx` directory, e.g. `steamapps/compatdata/<appid>/pfx`.
pub fn plugins_txt_dir(prefix: &Path, spec: &GameSpec) -> PathBuf {
    prefix
        .join("drive_c/users/steamuser/AppData/Local")
        .join(&spec.local_dir)
}

/// The game's `Documents/My Games/<game>/` directory inside a Proton prefix,
/// where the `.ini` files live (for the per-game-features work).
pub fn documents_my_games_dir(prefix: &Path, spec: &GameSpec) -> PathBuf {
    prefix
        .join("drive_c/users/steamuser/Documents/My Games")
        .join(&spec.local_dir)
}

impl PluginList {
    /// Write `plugins.txt` (+ `loadorder.txt`) into `dir` in the game's format.
    ///
    /// Asterisk games (Skyrim SE, FO4, Starfield): `plugins.txt` lists every
    /// non-primary plugin in load order, active ones prefixed `*`; the implicit
    /// base masters (`Skyrim.esm` ...) are omitted, exactly as MO2 writes them.
    /// Plain games (Skyrim LE, FO3, FNV): `plugins.txt` lists just the active
    /// plugins. `loadorder.txt` always holds the full order, unprefixed.
    ///
    /// Returns how many plugins were LISTED in plugins.txt. On a stock
    /// Anniversary install that is a handful out of nearly ninety - the engine
    /// loads the primaries and the `.ccc` Creations by itself - and a launch
    /// message that reported the in-memory active count as "written" sent a whole
    /// investigation towards a 7-line file that was never wrong.
    pub fn write_load_order(&self, dir: &Path, spec: &GameSpec) -> io::Result<usize> {
        // MO2 refuses to commit an empty list (gamebryogameplugins.cpp:136): a
        // momentarily-unreadable Data dir yields no plugins, and overwriting a good
        // plugins.txt with a header-only file would wipe the user's load order.
        if self.plugins.is_empty() {
            return Ok(0);
        }
        fs::create_dir_all(dir)?;

        // Plugins the engine loads by itself must not appear in plugins.txt: the
        // primary masters, and the Creation Club content named in the game's
        // `.ccc` (see `implicit_plugins` for what listing those anyway costs).
        let mut primaries: std::collections::HashSet<String> = spec
            .primary_plugins
            .iter()
            .map(|s| s.to_ascii_lowercase())
            .collect();
        primaries.extend(self.implicit.iter().cloned());

        // MO2 writes both files CRLF; plugins.txt in the Windows ANSI codepage
        // (Encoding::System -> CP1252 on Western locales), loadorder.txt UTF-8.
        let mut plugins = format!("{HEADER}\r\n");
        let mut listed = 0usize;
        match spec.mechanism {
            LoadOrderMechanism::Asterisk => {
                for p in &self.plugins {
                    if primaries.contains(&p.name.to_ascii_lowercase()) {
                        continue;
                    }
                    if p.enabled {
                        plugins.push('*');
                    }
                    plugins.push_str(&p.name);
                    plugins.push_str("\r\n");
                    listed += 1;
                }
            }
            LoadOrderMechanism::PlainList => {
                for p in self.plugins.iter().filter(|p| p.enabled) {
                    plugins.push_str(&p.name);
                    plugins.push_str("\r\n");
                    listed += 1;
                }
            }
        }
        let (cp1252, _, _) = encoding_rs::WINDOWS_1252.encode(&plugins);
        write_atomic(&canonical_path(dir, "plugins.txt"), &cp1252)?;

        let mut order = format!("{HEADER}\r\n");
        for p in &self.plugins {
            order.push_str(&p.name);
            order.push_str("\r\n");
        }
        write_atomic(&canonical_path(dir, "loadorder.txt"), order.as_bytes())?;
        Ok(listed)
    }

    /// Parse `plugins.txt` in `dir`: `(name, enabled)` pairs in file order. For
    /// asterisk games a leading `*` means active; for plain games every listed
    /// plugin is active. A missing/unreadable file yields an empty vec.
    pub fn read_active(dir: &Path, spec: &GameSpec) -> Vec<(String, bool)> {
        let Some(text) = newest_variant(dir, "plugins.txt").and_then(|p| read_decoded(&p)) else {
            return Vec::new();
        };
        let mut out = Vec::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            match spec.mechanism {
                LoadOrderMechanism::Asterisk => match line.strip_prefix('*') {
                    Some(name) => out.push((name.to_string(), true)),
                    None => out.push((line.to_string(), false)),
                },
                LoadOrderMechanism::PlainList => out.push((line.to_string(), true)),
            }
        }
        out
    }

    /// The full saved order from `loadorder.txt` (unprefixed names, file order).
    /// Header/blank lines skipped; a missing file yields an empty vec. For
    /// PlainList games this is the only record of where INACTIVE plugins sit.
    pub fn read_load_order(dir: &Path) -> Vec<String> {
        let Some(text) = newest_variant(dir, "loadorder.txt").and_then(|p| read_decoded(&p)) else {
            return Vec::new();
        };
        text.lines()
            .map(str::trim)
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .map(String::from)
            .collect()
    }

    /// Apply the saved on-disk state from a prefix `dir` onto the discovered list
    /// (order + enabled).
    ///
    /// For BOTH mechanisms, `loadorder.txt` is the ORDER authority and
    /// `plugins.txt` supplies the enabled flags. This split is MO2's
    /// (`GamebryoGamePlugins`: loadorder.txt = order, plugins.txt = active), and
    /// on an Asterisk game it is not a stylistic choice: `plugins.txt`
    /// deliberately omits the primaries and every `.ccc` Creation - the engine
    /// loads those by itself - which on a stock Anniversary install is ~80 of ~87
    /// plugins. Treating `plugins.txt` as the order authority therefore rebuilt
    /// nearly the whole order from discovery (alphabetical), which is what
    /// silently reverted every LOOT sort before the game even started.
    ///
    /// For PlainList games there is a second duty: `plugins.txt` lists only the
    /// actives, so a plugin present in `loadorder.txt` but absent from a
    /// non-empty `plugins.txt` is one the user DISABLED - it must stay disabled
    /// (MO2's "unlisted = inactive"), not silently re-enable on the next launch.
    /// A plugin in neither file is genuinely new and keeps its discovered default.
    pub fn apply_prefix_state(&mut self, dir: &Path, spec: &GameSpec) {
        use std::collections::{HashMap, HashSet};
        let active = Self::read_active(dir, spec);
        match spec.mechanism {
            LoadOrderMechanism::Asterisk => {
                // Flags first (also orders the listed subset)...
                if !active.is_empty() {
                    self.apply_active(&active);
                }
                // ...then the FULL order from loadorder.txt overrides. The sort is
                // stable, so plugins missing from it (installed since the last
                // write) keep their relative position and land last; `refresh`
                // then places them within the engine invariants.
                let order = Self::read_load_order(dir);
                if !order.is_empty() {
                    let pos: HashMap<String, usize> = order
                        .iter()
                        .enumerate()
                        .map(|(i, n)| (n.to_ascii_lowercase(), i))
                        .collect();
                    self.plugins.sort_by_key(|p| {
                        pos.get(&p.name.to_ascii_lowercase())
                            .copied()
                            .unwrap_or(usize::MAX)
                    });

                    // One exception to loadorder.txt's authority: Eidos writes the
                    // two files together, so when plugins.txt is strictly NEWER
                    // something else - the game via the bound dir, or xEdit run
                    // through the view - rewrote it alone, and its relative order
                    // for the plugins it lists is the fresher truth. Those plugins
                    // are re-dealt into the SLOTS they already occupy, in
                    // plugins.txt order; everything else (primaries, Creations)
                    // keeps its loadorder.txt position.
                    if !active.is_empty() && plugins_txt_is_newer(dir) {
                        let listed: HashMap<String, usize> = active
                            .iter()
                            .enumerate()
                            .map(|(i, (n, _))| (n.to_ascii_lowercase(), i))
                            .collect();
                        let slots: Vec<usize> = self
                            .plugins
                            .iter()
                            .enumerate()
                            .filter(|(_, p)| listed.contains_key(&p.name.to_ascii_lowercase()))
                            .map(|(i, _)| i)
                            .collect();
                        let mut members: Vec<crate::Plugin> =
                            slots.iter().map(|&i| self.plugins[i].clone()).collect();
                        members.sort_by_key(|p| listed[&p.name.to_ascii_lowercase()]);
                        for (&slot, m) in slots.iter().zip(members) {
                            self.plugins[slot] = m;
                        }
                    }
                }
            }
            LoadOrderMechanism::PlainList => {
                let order = Self::read_load_order(dir);
                if active.is_empty() && order.is_empty() {
                    return; // nothing saved yet
                }
                let active_set: HashSet<String> =
                    active.iter().map(|(n, _)| n.to_ascii_lowercase()).collect();
                let order_set: HashSet<String> =
                    order.iter().map(|s| s.to_ascii_lowercase()).collect();
                let primaries: HashSet<String> = spec
                    .primary_plugins
                    .iter()
                    .map(|s| s.to_ascii_lowercase())
                    .collect();
                let plugins_txt_present = !active.is_empty();
                for p in &mut self.plugins {
                    let lname = p.name.to_ascii_lowercase();
                    if active_set.contains(&lname) {
                        // A force-disabled .esl can never be activated, even if a stale
                        // plugins.txt lists it.
                        p.enabled = !p.force_disabled;
                    } else if plugins_txt_present
                        && order_set.contains(&lname)
                        && !primaries.contains(&lname)
                    {
                        // listed in loadorder.txt but not active in plugins.txt
                        p.enabled = false;
                    }
                }
                let pos: HashMap<String, usize> = order
                    .iter()
                    .enumerate()
                    .map(|(i, n)| (n.to_ascii_lowercase(), i))
                    .collect();
                self.plugins.sort_by_key(|p| {
                    pos.get(&p.name.to_ascii_lowercase())
                        .copied()
                        .unwrap_or(usize::MAX)
                });
            }
        }
    }

    /// Apply a previously-saved active set: set each matching plugin's enabled
    /// state and reorder to the saved order (plugins absent from the set keep
    /// their relative order, placed last). Call `refresh` afterwards to
    /// re-validate the invariants and recompute indexes.
    pub fn apply_active(&mut self, active: &[(String, bool)]) {
        use std::collections::HashMap;
        let enabled: HashMap<String, bool> = active
            .iter()
            .map(|(n, e)| (n.to_ascii_lowercase(), *e))
            .collect();
        let pos: HashMap<String, usize> = active
            .iter()
            .enumerate()
            .map(|(i, (n, _))| (n.to_ascii_lowercase(), i))
            .collect();
        for p in &mut self.plugins {
            if let Some(&e) = enabled.get(&p.name.to_ascii_lowercase()) {
                p.enabled = e && !p.force_disabled;
            }
        }
        self.plugins.sort_by_key(|p| {
            pos.get(&p.name.to_ascii_lowercase())
                .copied()
                .unwrap_or(usize::MAX)
        });
    }
}

/// The path to WRITE a prefix control file at, collapsing case variants.
///
/// The prefix lives on a case-sensitive filesystem while the game came from a
/// case-insensitive one, so `Plugins.txt` and `plugins.txt` can both exist and
/// the game may read the one Eidos did not write. Wine resolves a missing exact
/// name by scanning the directory, so ONE file is always enough - which makes
/// collapsing strictly safer than keeping several in sync.
///
/// Keeps whichever spelling already exists (the game chose it), preferring the
/// most recently written when several do, and deletes the losers so they cannot
/// be read back later. Scoped to the caller's own directory and filename.
pub fn canonical_path(dir: &Path, name: &str) -> PathBuf {
    let mut variants: Vec<PathBuf> = case_variants(dir, name);
    if variants.is_empty() {
        return dir.join(name);
    }
    // Newest first: that is the file the game actually wrote.
    variants.sort_by_key(|p| {
        std::cmp::Reverse(
            fs::metadata(p)
                .and_then(|m| m.modified())
                .unwrap_or(std::time::UNIX_EPOCH),
        )
    });
    let keep = variants.remove(0);
    for stale in variants {
        match fs::remove_file(&stale) {
            Ok(()) => eprintln!(
                "eidos: removed a stale case variant {} (keeping {})",
                stale.display(),
                keep.display()
            ),
            Err(e) => eprintln!("eidos: could not remove {}: {e}", stale.display()),
        }
    }
    keep
}

/// The path to READ a prefix control file from: the newest existing case
/// variant, or `None` when there is none.
pub fn newest_variant(dir: &Path, name: &str) -> Option<PathBuf> {
    case_variants(dir, name)
        .into_iter()
        .max_by_key(|p| fs::metadata(p).and_then(|m| m.modified()).ok())
}

/// Whether `plugins.txt` was written strictly after `loadorder.txt`.
///
/// Eidos always writes plugins.txt first and loadorder.txt second, so its own
/// writes answer false; a true answer means someone rewrote plugins.txt ALONE -
/// the game through the bound dir, or a tool - and its ordering of the plugins
/// it lists is fresher than loadorder.txt's.
fn plugins_txt_is_newer(dir: &Path) -> bool {
    let mtime = |name: &str| {
        newest_variant(dir, name)
            .and_then(|p| fs::metadata(p).ok())
            .and_then(|m| m.modified().ok())
    };
    match (mtime("plugins.txt"), mtime("loadorder.txt")) {
        (Some(p), Some(l)) => p > l,
        _ => false,
    }
}

/// Every entry of `dir` whose name equals `name` ignoring ASCII case.
fn case_variants(dir: &Path, name: &str) -> Vec<PathBuf> {
    fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|e| {
            e.file_name()
                .to_str()
                .is_some_and(|n| n.eq_ignore_ascii_case(name))
                && e.path().is_file()
        })
        .map(|e| e.path())
        .collect()
}

/// Atomically replace `path`: write a sibling `.tmp` then rename over it (atomic
/// within one filesystem), so a crash mid-write cannot leave a partial plugins.txt
/// that the game would load with half the mods off.
fn write_atomic(path: &Path, bytes: &[u8]) -> io::Result<()> {
    // Unique per PROCESS and per call. A fixed name is not atomic against a
    // second WRITER: two processes share the one temp path, their bytes
    // interleave in it, and whichever renames last publishes the mixture. The
    // rename only makes the result all-or-nothing for READERS.
    static SEQ: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let tmp = path.with_extension(format!(
        "eidos-tmp.{}.{}",
        std::process::id(),
        SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    ));
    fs::write(&tmp, bytes)?;
    match fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(e) => {
            let _ = fs::remove_file(&tmp);
            Err(e)
        }
    }
}

/// Read a plugin-list file. `plugins.txt` is the Windows ANSI codepage (MO2's
/// `Encoding::System`): try UTF-8 first (our own ASCII output round-trips), then
/// fall back to CP1252 so a file MO2 or the game wrote with accented names is
/// decoded instead of discarded - discarding it would wipe the saved active set.
///
/// Public because EVERY reader of these files must use it: the capture guard
/// once read plugins.txt with plain `read_to_string`, and a single accented
/// plugin name - in the encoding Eidos itself writes - made the read fail and
/// silently disarmed the guard protecting the profile from a wipe.
pub fn read_decoded(path: &Path) -> Option<String> {
    let bytes = fs::read(path).ok()?;
    match std::str::from_utf8(&bytes) {
        Ok(s) => Some(s.to_string()),
        Err(_) => Some(encoding_rs::WINDOWS_1252.decode(&bytes).0.into_owned()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Plugin;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static N: AtomicUsize = AtomicUsize::new(0);

    fn tmp_dir() -> PathBuf {
        let n = N.fetch_add(1, Ordering::Relaxed);
        let d = std::env::temp_dir().join(format!("eidos-lo-{}-{}", std::process::id(), n));
        fs::create_dir_all(&d).unwrap();
        d
    }

    fn pl(name: &str, enabled: bool) -> Plugin {
        Plugin {
            name: name.to_string(),
            origin_mod: String::new(),
            path: PathBuf::from(name),
            enabled,
            force_disabled: false,
            is_master: name.to_ascii_lowercase().ends_with(".esm"),
            is_light: false,
            is_medium: false,
            masters: Vec::new(),
            priority: -1,
            index: None,
        }
    }

    fn se() -> GameSpec {
        GameSpec::for_id("skyrimse").unwrap()
    }

    #[test]
    fn creation_club_plugins_are_never_written_to_plugins_txt() {
        // The engine loads everything named in `Skyrim.ccc` by itself, exactly
        // like the primary masters, and a stock Anniversary install therefore has
        // an EMPTY plugins.txt. Listing them anyway makes the game see each
        // Creation twice and blank the whole file the moment it finishes loading,
        // after which the save-game Creation check and any mod script that asks
        // whether its plugin is present both read an empty list.
        let dir = tmp_dir();
        let spec = se();
        let mut list = PluginList {
            plugins: vec![
                pl("Skyrim.esm", true),
                pl("ccBGSSSE001-Fish.esm", true),
                pl("ccQDRSSE001-SurvivalMode.esl", true),
                pl("SkyUI_SE.esp", true),
            ],
            implicit: ["ccbgssse001-fish.esm", "ccqdrsse001-survivalmode.esl"]
                .into_iter()
                .map(String::from)
                .collect(),
            locked: Default::default(),
        };
        list.refresh(&spec);
        list.write_load_order(&dir, &spec).unwrap();

        let txt = fs::read_to_string(dir.join("plugins.txt")).unwrap();
        let lines: Vec<&str> = txt
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        // Only the real mod. Skyrim.esm is primary, the two cc* are implicit.
        assert_eq!(lines, vec!["*SkyUI_SE.esp"], "{txt}");

        // loadorder.txt still records everything - it is the full order, not the
        // active set, and MO2 writes it the same way.
        let order = fs::read_to_string(dir.join("loadorder.txt")).unwrap();
        assert!(order.contains("ccBGSSSE001-Fish.esm"), "{order}");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn resolver_paths() {
        let spec = se();
        let prefix = Path::new("/steam/compatdata/489830/pfx");
        assert_eq!(
            plugins_txt_dir(prefix, &spec),
            Path::new("/steam/compatdata/489830/pfx/drive_c/users/steamuser/AppData/Local/Skyrim Special Edition")
        );
        assert!(documents_my_games_dir(prefix, &spec)
            .ends_with("Documents/My Games/Skyrim Special Edition"));
    }

    #[test]
    fn asterisk_write_omits_primaries_and_marks_active() {
        let dir = tmp_dir();
        let list = PluginList {
            plugins: vec![
                pl("Skyrim.esm", true), // primary -> omitted from plugins.txt
                pl("ActiveMod.esp", true),
                pl("OffMod.esp", false),
            ],
            implicit: Default::default(),
            locked: Default::default(),
        };
        list.write_load_order(&dir, &se()).unwrap();

        let plugins = fs::read_to_string(dir.join("plugins.txt")).unwrap();
        assert_eq!(
            plugins,
            "# This file was automatically generated by Eidos.\r\n*ActiveMod.esp\r\nOffMod.esp\r\n"
        );
        // loadorder.txt keeps everything, including the primary, unprefixed.
        let order = fs::read_to_string(dir.join("loadorder.txt")).unwrap();
        assert_eq!(
            order,
            "# This file was automatically generated by Eidos.\r\nSkyrim.esm\r\nActiveMod.esp\r\nOffMod.esp\r\n"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn read_active_round_trips_the_enabled_set() {
        let dir = tmp_dir();
        let list = PluginList {
            plugins: vec![
                pl("Skyrim.esm", true),
                pl("A.esp", true),
                pl("B.esp", false),
            ],
            implicit: Default::default(),
            locked: Default::default(),
        };
        list.write_load_order(&dir, &se()).unwrap();

        let active = PluginList::read_active(&dir, &se());
        // Skyrim.esm omitted (primary); A active, B inactive.
        assert_eq!(
            active,
            vec![("A.esp".to_string(), true), ("B.esp".to_string(), false)]
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn apply_active_sets_state_and_order() {
        let mut list = PluginList {
            plugins: vec![pl("B.esp", true), pl("A.esp", true), pl("C.esp", true)],
            implicit: Default::default(),
            locked: Default::default(),
        };
        list.apply_active(&[("A.esp".into(), true), ("B.esp".into(), false)]);
        // Order follows the applied list (A, B), then the rest (C); B now off.
        let names: Vec<_> = list
            .plugins
            .iter()
            .map(|p| (p.name.clone(), p.enabled))
            .collect();
        assert_eq!(
            names,
            vec![
                ("A.esp".into(), true),
                ("B.esp".into(), false),
                ("C.esp".into(), true)
            ]
        );
    }

    #[test]
    fn force_disabled_plugin_never_activated_by_prefix_state() {
        // A force-disabled .esl must stay off even if a stale plugins.txt lists it
        // active (it would otherwise consume an index slot it can't legally have).
        let mut esl = pl("Light.esl", false);
        esl.force_disabled = true;
        let mut list = PluginList {
            plugins: vec![esl, pl("Normal.esp", false)],
            implicit: Default::default(),
            locked: Default::default(),
        };
        list.apply_active(&[("Light.esl".into(), true), ("Normal.esp".into(), true)]);
        let light = list.plugins.iter().find(|p| p.name == "Light.esl").unwrap();
        let normal = list
            .plugins
            .iter()
            .find(|p| p.name == "Normal.esp")
            .unwrap();
        assert!(
            !light.enabled,
            "force-disabled stays off despite an active listing"
        );
        assert!(
            normal.enabled,
            "a normal plugin still honours the active listing"
        );
    }

    #[test]
    fn plain_list_writes_active_names_only() {
        let dir = tmp_dir();
        let spec = GameSpec::for_id("skyrim").unwrap(); // PlainList
        let list = PluginList {
            plugins: vec![
                pl("Skyrim.esm", true),
                pl("On.esp", true),
                pl("Off.esp", false),
            ],
            implicit: Default::default(),
            locked: Default::default(),
        };
        list.write_load_order(&dir, &spec).unwrap();
        let plugins = fs::read_to_string(dir.join("plugins.txt")).unwrap();
        // Plain: active names only, no `*`, primaries included.
        assert_eq!(
            plugins,
            "# This file was automatically generated by Eidos.\r\nSkyrim.esm\r\nOn.esp\r\n"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn plugins_txt_round_trips_a_cp1252_name() {
        let dir = tmp_dir();
        let list = PluginList {
            plugins: vec![pl("Caf\u{e9} Society.esp", true), pl("Plain.esp", false)],
            implicit: Default::default(),
            locked: Default::default(),
        };
        list.write_load_order(&dir, &se()).unwrap();
        // The on-disk bytes are CP1252 (é = 0xE9), not UTF-8.
        let raw = fs::read(dir.join("plugins.txt")).unwrap();
        assert!(raw.contains(&0xE9), "accented name must be CP1252-encoded");
        assert!(
            std::str::from_utf8(&raw).is_err(),
            "plugins.txt is not valid UTF-8"
        );
        // ...and read_active decodes it back instead of discarding the file.
        let active = PluginList::read_active(&dir, &se());
        assert_eq!(
            active,
            vec![
                ("Caf\u{e9} Society.esp".to_string(), true),
                ("Plain.esp".to_string(), false)
            ]
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_case_variant_in_the_prefix_is_read_and_collapsed() {
        let dir = std::env::temp_dir().join(format!("eidos-cv-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        // The game wrote `Plugins.txt`; Eidos has always written `plugins.txt`.
        // Reading the hard-coded lowercase name would miss the game's own file.
        fs::write(dir.join("Plugins.txt"), b"*FromGame.esp\r\n").unwrap();
        let spec = GameSpec::for_id("skyrimse").unwrap();
        let active = PluginList::read_active(&dir, &spec);
        assert_eq!(active, vec![("FromGame.esp".to_string(), true)]);

        // Writing keeps the spelling the game chose rather than adding a second
        // file the game might read instead.
        let mut list = PluginList {
            plugins: vec![],
            implicit: Default::default(),
            locked: Default::default(),
        };
        list.plugins.push(crate::Plugin {
            name: "Written.esp".into(),
            origin_mod: String::new(),
            path: PathBuf::new(),
            enabled: true,
            force_disabled: false,
            is_master: false,
            is_light: false,
            is_medium: false,
            masters: vec![],
            priority: 0,
            index: None,
        });
        list.write_load_order(&dir, &spec).unwrap();
        let variants: Vec<String> = fs::read_dir(&dir)
            .unwrap()
            .flatten()
            .filter_map(|e| e.file_name().into_string().ok())
            .filter(|n| n.eq_ignore_ascii_case("plugins.txt"))
            .collect();
        assert_eq!(
            variants,
            vec!["Plugins.txt".to_string()],
            "must not create a second variant"
        );
        assert!(read_decoded(&dir.join("Plugins.txt"))
            .unwrap()
            .contains("Written.esp"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn several_variants_collapse_to_the_newest() {
        let dir = std::env::temp_dir().join(format!("eidos-cv2-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("plugins.txt"), b"*old.esp\r\n").unwrap();
        std::thread::sleep(std::time::Duration::from_millis(20));
        fs::write(dir.join("Plugins.txt"), b"*new.esp\r\n").unwrap();

        let spec = GameSpec::for_id("skyrimse").unwrap();
        // The newest is what the game last wrote, so it is the truth.
        assert_eq!(
            PluginList::read_active(&dir, &spec),
            vec![("new.esp".to_string(), true)]
        );

        // A write collapses to one file, so nothing stale can be read later.
        // (Non-empty: writing an empty list is refused by design, so it would
        // never reach the collapse.)
        let list = PluginList {
            plugins: vec![crate::Plugin {
                name: "new.esp".into(),
                origin_mod: String::new(),
                path: PathBuf::new(),
                enabled: true,
                force_disabled: false,
                is_master: false,
                is_light: false,
                is_medium: false,
                masters: vec![],
                priority: 0,
                index: None,
            }],
            implicit: Default::default(),
            locked: Default::default(),
        };
        list.write_load_order(&dir, &spec).unwrap();
        let n = fs::read_dir(&dir)
            .unwrap()
            .flatten()
            .filter(|e| {
                e.file_name()
                    .to_string_lossy()
                    .eq_ignore_ascii_case("plugins.txt")
            })
            .count();
        assert_eq!(n, 1, "case variants must be collapsed, not left to drift");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn empty_list_does_not_overwrite_plugins_txt() {
        let dir = tmp_dir();
        fs::write(dir.join("plugins.txt"), b"# precious\n*KeepMe.esp\n").unwrap();
        PluginList {
            plugins: vec![],
            implicit: Default::default(),
            locked: Default::default(),
        }
        .write_load_order(&dir, &se())
        .unwrap();
        // MO2 refuses to write an empty list; the good file is untouched.
        assert_eq!(
            fs::read_to_string(dir.join("plugins.txt")).unwrap(),
            "# precious\n*KeepMe.esp\n"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    /// The reported bug, end to end: a LOOT sort places the Creation Club content
    /// in `.ccc` file order (NOT alphabetical) and the whole order is written; the
    /// next state round-trip must come back in that order, not reverted.
    ///
    /// The trap: plugins.txt deliberately omits primaries and Creations - on a
    /// real Anniversary install that is ~80 of ~87 plugins - so the file cannot
    /// order them. Only loadorder.txt can. Reading plugins.txt as the order
    /// authority rebuilt those ~80 from discovery order (alphabetical), reverted
    /// both files pre-launch, and the user re-sorted every single session.
    #[test]
    fn a_loot_sorted_order_survives_the_state_round_trip() {
        let dir = tmp_dir();
        let spec = se();
        let implicit: std::collections::HashSet<String> =
            ["cczeta.esl".to_string(), "ccalpha.esl".to_string()]
                .into_iter()
                .collect();

        // LOOT's verdict: Zeta BEFORE Alpha (`.ccc` file order beats alphabetical).
        let mut sorted = PluginList {
            plugins: vec![
                pl("Skyrim.esm", true),
                pl("ccZeta.esl", true),
                pl("ccAlpha.esl", true),
                pl("MyMod.esp", true),
            ],
            implicit: implicit.clone(),
            locked: Default::default(),
        };
        sorted.refresh(&spec);
        sorted.write_load_order(&dir, &spec).unwrap();
        // Precondition of the trap: plugins.txt holds ONLY the real mod.
        let txt = read_decoded(&dir.join("plugins.txt")).unwrap();
        let listed: Vec<&str> = txt
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        assert_eq!(listed, vec!["*MyMod.esp"], "{txt}");

        // A fresh discovery is alphabetical - the reverted order the bug produced.
        let mut fresh = PluginList {
            plugins: vec![
                pl("ccAlpha.esl", true),
                pl("ccZeta.esl", true),
                pl("MyMod.esp", true),
                pl("Skyrim.esm", true),
            ],
            implicit,
            locked: Default::default(),
        };
        fresh.apply_prefix_state(&dir, &spec);
        fresh.refresh(&spec);

        let names: Vec<&str> = fresh.plugins.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["Skyrim.esm", "ccZeta.esl", "ccAlpha.esl", "MyMod.esp"],
            "the LOOT order must survive; alphabetical here means the revert is back"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    /// When something rewrote plugins.txt ALONE (the game through the bound dir,
    /// xEdit through the view), its relative order for the plugins it lists is
    /// fresher than loadorder.txt's - those plugins follow it, everything else
    /// keeps its loadorder.txt slot.
    #[test]
    fn a_fresher_plugins_txt_wins_the_order_for_the_plugins_it_lists() {
        let dir = tmp_dir();
        let spec = se();
        let saved = PluginList {
            plugins: vec![
                pl("Skyrim.esm", true),
                pl("A.esp", true),
                pl("B.esp", true),
                pl("C.esp", true),
            ],
            implicit: Default::default(),
            locked: Default::default(),
        };
        saved.write_load_order(&dir, &spec).unwrap();

        // The game/xEdit rewrites plugins.txt alone, reordering: C, A, B.
        std::thread::sleep(std::time::Duration::from_millis(20));
        fs::write(dir.join("plugins.txt"), b"*C.esp\r\n*A.esp\r\n*B.esp\r\n").unwrap();

        let mut fresh = PluginList {
            plugins: vec![
                pl("A.esp", true),
                pl("B.esp", true),
                pl("C.esp", true),
                pl("Skyrim.esm", true),
            ],
            implicit: Default::default(),
            locked: Default::default(),
        };
        fresh.apply_prefix_state(&dir, &spec);
        let names: Vec<&str> = fresh.plugins.iter().map(|p| p.name.as_str()).collect();
        // Skyrim.esm keeps its loadorder slot (first); the listed three follow
        // the fresher plugins.txt order in the slots they occupied.
        assert_eq!(names, vec!["Skyrim.esm", "C.esp", "A.esp", "B.esp"]);
        let _ = fs::remove_dir_all(&dir);
    }

    /// The normal case - Eidos wrote both files together - must NOT trip the
    /// freshness exception: loadorder.txt stays the authority.
    #[test]
    fn a_joint_write_keeps_loadorder_as_the_authority() {
        let dir = tmp_dir();
        let spec = se();
        let saved = PluginList {
            plugins: vec![pl("Skyrim.esm", true), pl("B.esp", true), pl("A.esp", true)],
            implicit: Default::default(),
            locked: Default::default(),
        };
        saved.write_load_order(&dir, &spec).unwrap();

        let mut fresh = PluginList {
            plugins: vec![pl("A.esp", true), pl("B.esp", true), pl("Skyrim.esm", true)],
            implicit: Default::default(),
            locked: Default::default(),
        };
        fresh.apply_prefix_state(&dir, &spec);
        let names: Vec<&str> = fresh.plugins.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(names, vec!["Skyrim.esm", "B.esp", "A.esp"]);
        let _ = fs::remove_dir_all(&dir);
    }

    /// A plugin installed after the last write is in neither file: it must keep
    /// its discovered position at the end, not scramble the saved order.
    #[test]
    fn a_new_plugin_lands_after_the_saved_order() {
        let dir = tmp_dir();
        let spec = se();
        let saved = PluginList {
            plugins: vec![pl("Skyrim.esm", true), pl("B.esp", true), pl("A.esp", true)],
            implicit: Default::default(),
            locked: Default::default(),
        };
        saved.write_load_order(&dir, &spec).unwrap();

        let mut fresh = PluginList {
            plugins: vec![
                pl("A.esp", true),
                pl("B.esp", true),
                pl("New.esp", true),
                pl("Skyrim.esm", true),
            ],
            implicit: Default::default(),
            locked: Default::default(),
        };
        fresh.apply_prefix_state(&dir, &spec);
        fresh.refresh(&spec);
        let names: Vec<&str> = fresh.plugins.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(names, vec!["Skyrim.esm", "B.esp", "A.esp", "New.esp"]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn plainlist_disabled_plugin_stays_disabled_via_loadorder() {
        let dir = tmp_dir();
        let spec = GameSpec::for_id("skyrim").unwrap(); // PlainList
                                                        // Saved: order = A,B,C; plugins.txt actives only A and C (B is off).
        PluginList {
            plugins: vec![pl("A.esp", true), pl("B.esp", false), pl("C.esp", true)],
            implicit: Default::default(),
            locked: Default::default(),
        }
        .write_load_order(&dir, &spec)
        .unwrap();

        // A fresh list in arbitrary order; prefix state decides enabled/disabled.
        let mut fresh = PluginList {
            plugins: vec![pl("C.esp", true), pl("A.esp", true), pl("B.esp", true)],
            implicit: Default::default(),
            locked: Default::default(),
        };
        fresh.apply_prefix_state(&dir, &spec);
        let state: Vec<_> = fresh
            .plugins
            .iter()
            .map(|p| (p.name.clone(), p.enabled))
            .collect();
        // Order follows loadorder.txt (A,B,C); B stays DISABLED (in loadorder.txt
        // but not plugins.txt) instead of silently re-enabling.
        assert_eq!(
            state,
            vec![
                ("A.esp".into(), true),
                ("B.esp".into(), false),
                ("C.esp".into(), true)
            ]
        );
        let _ = fs::remove_dir_all(&dir);
    }
}
