//! On-disk plugin load order: the Proton-prefix path resolver plus reading and
//! writing `plugins.txt` / `loadorder.txt` in the formats the games expect.
//!
//! These files do NOT live in the Data dir Eidos mounts over - they live in the
//! game's local AppData inside the Proton prefix:
//!   `<prefix>/drive_c/users/steamuser/AppData/Local/<game>/`
//! Eidos writes them there right before launch. The format here was verified
//! against a real MO2-generated Skyrim SE load order.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::{GameSpec, LoadOrderMechanism, PluginList};

const HEADER: &str = "# This file was automatically generated by Eidos.";

/// The directory holding `plugins.txt` / `loadorder.txt` inside a Proton prefix.
/// `prefix` is the `pfx` directory, e.g. `steamapps/compatdata/<appid>/pfx`.
pub fn plugins_txt_dir(prefix: &Path, spec: &GameSpec) -> PathBuf {
    prefix
        .join("drive_c/users/steamuser/AppData/Local")
        .join(&spec.local_dir)
}

/// The game's `Documents/My Games/<game>/` directory inside a Proton prefix,
/// where the `.ini` files live (for the per-game-features work).
pub fn documents_my_games_dir(prefix: &Path, spec: &GameSpec) -> PathBuf {
    prefix
        .join("drive_c/users/steamuser/Documents/My Games")
        .join(&spec.local_dir)
}

impl PluginList {
    /// Write `plugins.txt` (+ `loadorder.txt`) into `dir` in the game's format.
    ///
    /// Asterisk games (Skyrim SE, FO4, Starfield): `plugins.txt` lists every
    /// non-primary plugin in load order, active ones prefixed `*`; the implicit
    /// base masters (`Skyrim.esm` ...) are omitted, exactly as MO2 writes them.
    /// Plain games (Skyrim LE, FO3, FNV): `plugins.txt` lists just the active
    /// plugins. `loadorder.txt` always holds the full order, unprefixed.
    pub fn write_load_order(&self, dir: &Path, spec: &GameSpec) -> io::Result<()> {
        // MO2 refuses to commit an empty list (gamebryogameplugins.cpp:136): a
        // momentarily-unreadable Data dir yields no plugins, and overwriting a good
        // plugins.txt with a header-only file would wipe the user's load order.
        if self.plugins.is_empty() {
            return Ok(());
        }
        fs::create_dir_all(dir)?;

        let primaries: std::collections::HashSet<String> =
            spec.primary_plugins.iter().map(|s| s.to_ascii_lowercase()).collect();

        // MO2 writes both files CRLF; plugins.txt in the Windows ANSI codepage
        // (Encoding::System -> CP1252 on Western locales), loadorder.txt UTF-8.
        let mut plugins = format!("{HEADER}\r\n");
        match spec.mechanism {
            LoadOrderMechanism::Asterisk => {
                for p in &self.plugins {
                    if primaries.contains(&p.name.to_ascii_lowercase()) {
                        continue;
                    }
                    if p.enabled {
                        plugins.push('*');
                    }
                    plugins.push_str(&p.name);
                    plugins.push_str("\r\n");
                }
            }
            LoadOrderMechanism::PlainList => {
                for p in self.plugins.iter().filter(|p| p.enabled) {
                    plugins.push_str(&p.name);
                    plugins.push_str("\r\n");
                }
            }
        }
        let (cp1252, _, _) = encoding_rs::WINDOWS_1252.encode(&plugins);
        write_atomic(&dir.join("plugins.txt"), &cp1252)?;

        let mut order = format!("{HEADER}\r\n");
        for p in &self.plugins {
            order.push_str(&p.name);
            order.push_str("\r\n");
        }
        write_atomic(&dir.join("loadorder.txt"), order.as_bytes())?;
        Ok(())
    }

    /// Parse `plugins.txt` in `dir`: `(name, enabled)` pairs in file order. For
    /// asterisk games a leading `*` means active; for plain games every listed
    /// plugin is active. A missing/unreadable file yields an empty vec.
    pub fn read_active(dir: &Path, spec: &GameSpec) -> Vec<(String, bool)> {
        let Some(text) = read_decoded(&dir.join("plugins.txt")) else {
            return Vec::new();
        };
        let mut out = Vec::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            match spec.mechanism {
                LoadOrderMechanism::Asterisk => match line.strip_prefix('*') {
                    Some(name) => out.push((name.to_string(), true)),
                    None => out.push((line.to_string(), false)),
                },
                LoadOrderMechanism::PlainList => out.push((line.to_string(), true)),
            }
        }
        out
    }

    /// The full saved order from `loadorder.txt` (unprefixed names, file order).
    /// Header/blank lines skipped; a missing file yields an empty vec. For
    /// PlainList games this is the only record of where INACTIVE plugins sit.
    pub fn read_load_order(dir: &Path) -> Vec<String> {
        let Some(text) = read_decoded(&dir.join("loadorder.txt")) else {
            return Vec::new();
        };
        text.lines()
            .map(str::trim)
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .map(String::from)
            .collect()
    }

    /// Apply the saved on-disk state from a prefix `dir` onto the discovered list
    /// (order + enabled). For Asterisk games `plugins.txt` round-trips both active
    /// (`*`) and inactive lines, so this is just [`apply_active`]. For PlainList
    /// games `plugins.txt` lists only the actives, so `loadorder.txt` supplies the
    /// order and a plugin present there but absent from a non-empty `plugins.txt`
    /// is one the user DISABLED - it must stay disabled (MO2's "unlisted =
    /// inactive"), not silently re-enable on the next launch. A plugin in neither
    /// file is genuinely new and keeps its discovered default.
    pub fn apply_prefix_state(&mut self, dir: &Path, spec: &GameSpec) {
        use std::collections::{HashMap, HashSet};
        let active = Self::read_active(dir, spec);
        match spec.mechanism {
            LoadOrderMechanism::Asterisk => {
                if !active.is_empty() {
                    self.apply_active(&active);
                }
            }
            LoadOrderMechanism::PlainList => {
                let order = Self::read_load_order(dir);
                if active.is_empty() && order.is_empty() {
                    return; // nothing saved yet
                }
                let active_set: HashSet<String> =
                    active.iter().map(|(n, _)| n.to_ascii_lowercase()).collect();
                let order_set: HashSet<String> =
                    order.iter().map(|s| s.to_ascii_lowercase()).collect();
                let primaries: HashSet<String> =
                    spec.primary_plugins.iter().map(|s| s.to_ascii_lowercase()).collect();
                let plugins_txt_present = !active.is_empty();
                for p in &mut self.plugins {
                    let lname = p.name.to_ascii_lowercase();
                    if active_set.contains(&lname) {
                        p.enabled = true;
                    } else if plugins_txt_present && order_set.contains(&lname) && !primaries.contains(&lname) {
                        // listed in loadorder.txt but not active in plugins.txt
                        p.enabled = false;
                    }
                }
                let pos: HashMap<String, usize> =
                    order.iter().enumerate().map(|(i, n)| (n.to_ascii_lowercase(), i)).collect();
                self.plugins
                    .sort_by_key(|p| pos.get(&p.name.to_ascii_lowercase()).copied().unwrap_or(usize::MAX));
            }
        }
    }

    /// Apply a previously-saved active set: set each matching plugin's enabled
    /// state and reorder to the saved order (plugins absent from the set keep
    /// their relative order, placed last). Call `refresh` afterwards to
    /// re-validate the invariants and recompute indexes.
    pub fn apply_active(&mut self, active: &[(String, bool)]) {
        use std::collections::HashMap;
        let enabled: HashMap<String, bool> =
            active.iter().map(|(n, e)| (n.to_ascii_lowercase(), *e)).collect();
        let pos: HashMap<String, usize> =
            active.iter().enumerate().map(|(i, (n, _))| (n.to_ascii_lowercase(), i)).collect();
        for p in &mut self.plugins {
            if let Some(&e) = enabled.get(&p.name.to_ascii_lowercase()) {
                p.enabled = e;
            }
        }
        self.plugins
            .sort_by_key(|p| pos.get(&p.name.to_ascii_lowercase()).copied().unwrap_or(usize::MAX));
    }
}

/// Atomically replace `path`: write a sibling `.tmp` then rename over it (atomic
/// within one filesystem), so a crash mid-write cannot leave a partial plugins.txt
/// that the game would load with half the mods off.
fn write_atomic(path: &Path, bytes: &[u8]) -> io::Result<()> {
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, bytes)?;
    match fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(e) => {
            let _ = fs::remove_file(&tmp);
            Err(e)
        }
    }
}

/// Read a plugin-list file. `plugins.txt` is the Windows ANSI codepage (MO2's
/// `Encoding::System`): try UTF-8 first (our own ASCII output round-trips), then
/// fall back to CP1252 so a file MO2 or the game wrote with accented names is
/// decoded instead of discarded - discarding it would wipe the saved active set.
fn read_decoded(path: &Path) -> Option<String> {
    let bytes = fs::read(path).ok()?;
    match std::str::from_utf8(&bytes) {
        Ok(s) => Some(s.to_string()),
        Err(_) => Some(encoding_rs::WINDOWS_1252.decode(&bytes).0.into_owned()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Plugin;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static N: AtomicUsize = AtomicUsize::new(0);

    fn tmp_dir() -> PathBuf {
        let n = N.fetch_add(1, Ordering::Relaxed);
        let d = std::env::temp_dir().join(format!("eidos-lo-{}-{}", std::process::id(), n));
        fs::create_dir_all(&d).unwrap();
        d
    }

    fn pl(name: &str, enabled: bool) -> Plugin {
        Plugin {
            name: name.to_string(),
            origin_mod: String::new(),
            path: PathBuf::from(name),
            enabled,
            is_master: name.to_ascii_lowercase().ends_with(".esm"),
            is_light: false,
            is_medium: false,
            masters: Vec::new(),
            priority: -1,
            index: None,
        }
    }

    fn se() -> GameSpec {
        GameSpec::for_id("skyrimse").unwrap()
    }

    #[test]
    fn resolver_paths() {
        let spec = se();
        let prefix = Path::new("/steam/compatdata/489830/pfx");
        assert_eq!(
            plugins_txt_dir(prefix, &spec),
            Path::new("/steam/compatdata/489830/pfx/drive_c/users/steamuser/AppData/Local/Skyrim Special Edition")
        );
        assert!(documents_my_games_dir(prefix, &spec)
            .ends_with("Documents/My Games/Skyrim Special Edition"));
    }

    #[test]
    fn asterisk_write_omits_primaries_and_marks_active() {
        let dir = tmp_dir();
        let list = PluginList {
            plugins: vec![
                pl("Skyrim.esm", true),   // primary -> omitted from plugins.txt
                pl("ActiveMod.esp", true),
                pl("OffMod.esp", false),
            ],
        };
        list.write_load_order(&dir, &se()).unwrap();

        let plugins = fs::read_to_string(dir.join("plugins.txt")).unwrap();
        assert_eq!(
            plugins,
            "# This file was automatically generated by Eidos.\r\n*ActiveMod.esp\r\nOffMod.esp\r\n"
        );
        // loadorder.txt keeps everything, including the primary, unprefixed.
        let order = fs::read_to_string(dir.join("loadorder.txt")).unwrap();
        assert_eq!(
            order,
            "# This file was automatically generated by Eidos.\r\nSkyrim.esm\r\nActiveMod.esp\r\nOffMod.esp\r\n"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn read_active_round_trips_the_enabled_set() {
        let dir = tmp_dir();
        let list = PluginList {
            plugins: vec![pl("Skyrim.esm", true), pl("A.esp", true), pl("B.esp", false)],
        };
        list.write_load_order(&dir, &se()).unwrap();

        let active = PluginList::read_active(&dir, &se());
        // Skyrim.esm omitted (primary); A active, B inactive.
        assert_eq!(active, vec![("A.esp".to_string(), true), ("B.esp".to_string(), false)]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn apply_active_sets_state_and_order() {
        let mut list = PluginList {
            plugins: vec![pl("B.esp", true), pl("A.esp", true), pl("C.esp", true)],
        };
        list.apply_active(&[("A.esp".into(), true), ("B.esp".into(), false)]);
        // Order follows the applied list (A, B), then the rest (C); B now off.
        let names: Vec<_> = list.plugins.iter().map(|p| (p.name.clone(), p.enabled)).collect();
        assert_eq!(
            names,
            vec![("A.esp".into(), true), ("B.esp".into(), false), ("C.esp".into(), true)]
        );
    }

    #[test]
    fn plain_list_writes_active_names_only() {
        let dir = tmp_dir();
        let spec = GameSpec::for_id("skyrim").unwrap(); // PlainList
        let list = PluginList {
            plugins: vec![pl("Skyrim.esm", true), pl("On.esp", true), pl("Off.esp", false)],
        };
        list.write_load_order(&dir, &spec).unwrap();
        let plugins = fs::read_to_string(dir.join("plugins.txt")).unwrap();
        // Plain: active names only, no `*`, primaries included.
        assert_eq!(
            plugins,
            "# This file was automatically generated by Eidos.\r\nSkyrim.esm\r\nOn.esp\r\n"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn plugins_txt_round_trips_a_cp1252_name() {
        let dir = tmp_dir();
        let list = PluginList { plugins: vec![pl("Caf\u{e9} Society.esp", true), pl("Plain.esp", false)] };
        list.write_load_order(&dir, &se()).unwrap();
        // The on-disk bytes are CP1252 (é = 0xE9), not UTF-8.
        let raw = fs::read(dir.join("plugins.txt")).unwrap();
        assert!(raw.iter().any(|&b| b == 0xE9), "accented name must be CP1252-encoded");
        assert!(std::str::from_utf8(&raw).is_err(), "plugins.txt is not valid UTF-8");
        // ...and read_active decodes it back instead of discarding the file.
        let active = PluginList::read_active(&dir, &se());
        assert_eq!(
            active,
            vec![("Caf\u{e9} Society.esp".to_string(), true), ("Plain.esp".to_string(), false)]
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn empty_list_does_not_overwrite_plugins_txt() {
        let dir = tmp_dir();
        fs::write(dir.join("plugins.txt"), b"# precious\n*KeepMe.esp\n").unwrap();
        PluginList { plugins: vec![] }.write_load_order(&dir, &se()).unwrap();
        // MO2 refuses to write an empty list; the good file is untouched.
        assert_eq!(fs::read_to_string(dir.join("plugins.txt")).unwrap(), "# precious\n*KeepMe.esp\n");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn plainlist_disabled_plugin_stays_disabled_via_loadorder() {
        let dir = tmp_dir();
        let spec = GameSpec::for_id("skyrim").unwrap(); // PlainList
        // Saved: order = A,B,C; plugins.txt actives only A and C (B is off).
        PluginList { plugins: vec![pl("A.esp", true), pl("B.esp", false), pl("C.esp", true)] }
            .write_load_order(&dir, &spec)
            .unwrap();

        // A fresh discovery defaults everything enabled, in arbitrary order.
        let mut fresh =
            PluginList { plugins: vec![pl("C.esp", true), pl("A.esp", true), pl("B.esp", true)] };
        fresh.apply_prefix_state(&dir, &spec);
        let state: Vec<_> = fresh.plugins.iter().map(|p| (p.name.clone(), p.enabled)).collect();
        // Order follows loadorder.txt (A,B,C); B stays DISABLED (in loadorder.txt
        // but not plugins.txt) instead of silently re-enabling.
        assert_eq!(
            state,
            vec![("A.esp".into(), true), ("B.esp".into(), false), ("C.esp".into(), true)]
        );
        let _ = fs::remove_dir_all(&dir);
    }
}
