[package]
name = "eidos"
version.workspace = true
description = "Eidos: a native Linux mod manager (CLI front end)"
license.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "eidos"
path = "src/main.rs"

[dependencies]
eidos-games = { path = "../eidos-games" }
eidos-launch = { path = "../eidos-launch" }
eidos-instance = { path = "../eidos-instance" }
eidos-plugins = { path = "../eidos-plugins" }
eidos-loot = { path = "../eidos-loot" }
eidos-install = { path = "../eidos-install" }
eidos-gamefeatures = { path = "../eidos-gamefeatures" }
eidos-nexus = { path = "../eidos-nexus" }
