// Synthetic archive fixtures contain only generated bytes, never game assets.
use std::io::Write;

fn bsa_payload(
    version: u32,
    data: &[u8],
    compressed: bool,
    default: bool,
    prefix: bool,
) -> Vec<u8> {
    let mut b = bsa_fixture(version, "Textures/A.txt");
    let rec = if version == 105 { 60 } else { 52 };
    let rec = rec + 1 + b[rec] as usize;
    let offset = u32_at(&b, rec + 12) as usize;
    b.truncate(offset);
    let mut payload = Vec::new();
    if prefix {
        payload.extend_from_slice(b"\x0eTextures\\A.txt");
    }
    if compressed {
        payload.extend_from_slice(&11u32.to_le_bytes());
    }
    payload.extend_from_slice(data);
    put32(
        &mut b,
        12,
        3 | if default { 4 } else { 0 } | if prefix { 0x100 } else { 0 },
    );
    put32(
        &mut b,
        rec + 8,
        payload.len() as u32 | if compressed != default { 1 << 30 } else { 0 },
    );
    b.extend_from_slice(&payload);
    b
}
fn general_payload(version: u32, data: &[u8], unpacked: u32, compressed: bool) -> Vec<u8> {
    let mut b = ba2_fixture(version, false, "a.txt");
    let h = match version {
        2 => 32,
        3 => 36,
        _ => 24,
    };
    let offset = h + 36;
    b.splice(offset..offset + 1, data.iter().copied());
    put64(&mut b, 16, (offset + data.len()) as u64);
    put32(
        &mut b,
        h + 24,
        if compressed { data.len() as u32 } else { 0 },
    );
    put32(&mut b, h + 28, unpacked);
    b
}
fn member_bytes(bytes: &[u8], name: &str, limit: u64) -> Result<Vec<u8>> {
    let mut file = tempfile::tempfile().unwrap();
    file.write_all(bytes).unwrap();
    let mut output = Vec::new();
    let info = write_archive_member(&mut file, name, limit, &mut output)?;
    assert_eq!(info.bytes_written, output.len() as u64);
    Ok(output)
}
fn zlib_bytes(bytes: &[u8]) -> Vec<u8> {
    let mut encoder = flate2::write::ZlibEncoder::new(Vec::new(), flate2::Compression::default());
    encoder.write_all(bytes).unwrap();
    encoder.finish().unwrap()
}
fn frame_bytes(bytes: &[u8]) -> Vec<u8> {
    let info = lz4_flex::frame::FrameInfo::new()
        .content_checksum(true)
        .block_checksums(true);
    let mut encoder = lz4_flex::frame::FrameEncoder::with_frame_info(info, Vec::new());
    encoder.write_all(bytes).unwrap();
    encoder.finish().unwrap()
}
#[test]
fn payload_bsa_codec_toggle_prefix_and_exact_bytes() {
    // Python zlib.compress(b"hello world") gives this independent zlib fixture.
    let zlib = [
        120, 156, 203, 72, 205, 201, 201, 87, 40, 207, 47, 202, 73, 1, 0, 26, 11, 4, 93,
    ];
    for version in [103, 104, 105] {
        for default in [false, true] {
            for prefix in [false, true] {
                for compressed in [false, true] {
                    let encoded = if !compressed {
                        b"hello world".to_vec()
                    } else if version == 105 {
                        frame_bytes(b"hello world")
                    } else {
                        zlib.to_vec()
                    };
                    let b = bsa_payload(version, &encoded, compressed, default, prefix);
                    assert_eq!(
                        member_bytes(&b, "textures/a.TXT", 11).unwrap(),
                        b"hello world"
                    );
                    assert!(matches!(
                        member_bytes(&b, "Textures/A.txt", 10),
                        Err(ArchiveError::Limit(_))
                    ));
                }
            }
        }
    }
}
#[test]
fn payload_general_versions_use_zlib_even_in_starfield_v3() {
    for version in [1, 2, 3, 7, 8] {
        for compressed in [false, true] {
            let data = if compressed {
                zlib_bytes(b"hello world")
            } else {
                b"hello world".to_vec()
            };
            assert_eq!(
                member_bytes(
                    &general_payload(version, &data, 11, compressed),
                    "a.txt",
                    11
                )
                .unwrap(),
                b"hello world"
            );
        }
    }
    let mut gzip = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
    gzip.write_all(b"hello world").unwrap();
    assert_eq!(
        member_bytes(
            &general_payload(1, &gzip.finish().unwrap(), 11, true),
            "a.txt",
            11
        )
        .unwrap(),
        b"hello world"
    );
}
#[test]
fn payload_rejects_incomplete_streams_checksums_and_wrong_declared_size() {
    for version in [104, 105] {
        let bytes = if version == 105 {
            frame_bytes(b"hello world")
        } else {
            zlib_bytes(b"hello world")
        };
        for end in 0..bytes.len() {
            assert!(
                member_bytes(
                    &bsa_payload(version, &bytes[..end], true, false, false),
                    "textures/a.txt",
                    100
                )
                .is_err(),
                "{version} truncation {end}"
            );
        }
        for at in [bytes.len() - 1, bytes.len() / 2] {
            let mut broken = bytes.clone();
            broken[at] ^= 0x55;
            assert!(member_bytes(
                &bsa_payload(version, &broken, true, false, false),
                "textures/a.txt",
                100
            )
            .is_err());
        }
        let mut trailing = bytes;
        trailing.push(0);
        assert!(member_bytes(
            &bsa_payload(version, &trailing, true, false, false),
            "textures/a.txt",
            100
        )
        .is_err());
    }
    for declared in [10, 12, u32::MAX] {
        assert!(member_bytes(
            &general_payload(1, &zlib_bytes(b"hello world"), declared, true),
            "a.txt",
            100
        )
        .is_err());
    }
    assert!(member_bytes(
        &general_payload(1, b"hello world", 11, false),
        "../a.txt",
        100
    )
    .is_err());
    assert!(member_bytes(
        &general_payload(1, b"hello world", 11, false),
        "absent.txt",
        100
    )
    .is_err());
}

#[allow(clippy::too_many_arguments)]
fn texture_payload(
    version: u32,
    method: u32,
    format: u8,
    width: u16,
    height: u16,
    mips: u8,
    cube: bool,
    chunks: &[(u16, u16, Vec<u8>, u32, bool)],
) -> Vec<u8> {
    let header = match version {
        2 => 32,
        3 => 36,
        _ => 24,
    };
    let mut b = vec![0; header + 24 + chunks.len() * 24];
    b[..4].copy_from_slice(b"BTDX");
    put32(&mut b, 4, version);
    b[8..12].copy_from_slice(b"DX10");
    put32(&mut b, 12, 1);
    if version == 3 {
        put32(&mut b, 32, method);
    }
    b[header + 13] = chunks.len() as u8;
    b[header + 14] = 24;
    b[header + 16..header + 18].copy_from_slice(&height.to_le_bytes());
    b[header + 18..header + 20].copy_from_slice(&width.to_le_bytes());
    b[header + 20] = mips;
    b[header + 21] = format;
    b[header + 22] = u8::from(cube);
    b[header + 23] = 8;
    // Reverse physical chunks, with gaps, to catch assumptions about adjacency/order.
    for (i, (first, last, data, unpacked, compressed)) in chunks.iter().enumerate().rev() {
        b.extend_from_slice(&[0xfe; 7]);
        let offset = b.len() as u64;
        let rec = header + 24 + i * 24;
        put64(&mut b, rec, offset);
        put32(
            &mut b,
            rec + 8,
            if *compressed { data.len() as u32 } else { 0 },
        );
        put32(&mut b, rec + 12, *unpacked);
        b[rec + 16..rec + 18].copy_from_slice(&first.to_le_bytes());
        b[rec + 18..rec + 20].copy_from_slice(&last.to_le_bytes());
        b.extend_from_slice(data);
    }
    let names = b.len() as u64;
    put64(&mut b, 16, names);
    b.extend_from_slice(b"\x05\0a.dds");
    b
}
#[test]
fn payload_texture_reconstructs_dds_chunks_mips_and_cube_faces() {
    for (version, method) in [(1, 0), (2, 0), (3, 0), (3, 3), (7, 0), (8, 0)] {
        let encode = |data: &[u8]| {
            if method == 3 {
                lz4_flex::block::compress(data)
            } else {
                zlib_bytes(data)
            }
        };
        let chunks = [
            (1, 2, encode(&[2; 16]), 16, true),
            (0, 0, vec![1; 8], 8, false),
        ];
        let b = texture_payload(version, method, 72, 4, 4, 3, false, &chunks);
        let bytes = member_bytes(&b, "a.dds", 172).unwrap();
        let dds = ddsfile::Dds::read(&mut Cursor::new(&bytes)).unwrap();
        assert_eq!(
            (
                dds.get_width(),
                dds.get_height(),
                dds.get_num_mipmap_levels()
            ),
            (4, 4, 3)
        );
        assert_eq!(
            dds.get_dxgi_format(),
            Some(ddsfile::DxgiFormat::BC1_UNorm_sRGB)
        );
        assert_eq!(&bytes[148..156], &[1; 8]);
        assert_eq!(&bytes[156..], &[2; 16]);
        assert_eq!(dds.get_data(0).unwrap(), &bytes[148..]);
        assert!(matches!(
            member_bytes(&b, "a.dds", 171),
            Err(ArchiveError::Limit(_))
        ));
    }
    let top: Vec<_> = (0..6).flat_map(|face| [face * 10; 8]).collect();
    let tail: Vec<_> = (0..6)
        .flat_map(|face| [vec![face * 10 + 1; 8], vec![face * 10 + 2; 8]].concat())
        .collect();
    let b = texture_payload(
        3,
        3,
        71,
        4,
        4,
        3,
        true,
        &[
            (1, 2, lz4_flex::block::compress(&tail), 96, true),
            (0, 0, top, 48, false),
        ],
    );
    let bytes = member_bytes(&b, "a.dds", 292).unwrap();
    let dds = ddsfile::Dds::read(&mut Cursor::new(&bytes)).unwrap();
    assert_eq!(dds.header10.as_ref().unwrap().array_size, 1);
    assert!(dds
        .header10
        .as_ref()
        .unwrap()
        .misc_flag
        .contains(ddsfile::MiscFlag::TEXTURECUBE));
    assert_eq!(dds.get_num_array_layers(), 1); // DX10 stores cube count, not face count.
    for face in 0..6 {
        let expected = [
            vec![face * 10; 8],
            vec![face * 10 + 1; 8],
            vec![face * 10 + 2; 8],
        ]
        .concat();
        assert_eq!(
            &dds.data[face as usize * 24..(face as usize + 1) * 24],
            expected
        );
    }
}
#[test]
fn payload_texture_layout_and_malformed_chunk_guards() {
    // Five-by-three BC formats require TWO blocks, including at nonmultiples of four.
    for (format, bytes) in [
        (71, 16),
        (74, 32),
        (77, 32),
        (80, 16),
        (81, 16),
        (83, 32),
        (84, 32),
        (95, 32),
        (96, 32),
        (98, 32),
        (28, 60),
        (87, 60),
        (61, 15),
    ] {
        let b = texture_payload(
            1,
            0,
            format,
            5,
            3,
            1,
            false,
            &[(0, 0, vec![7; bytes], bytes as u32, false)],
        );
        let output = member_bytes(&b, "a.dds", 1024).unwrap();
        let dds = ddsfile::Dds::read(&mut Cursor::new(&output)).unwrap();
        assert_eq!(dds.get_data(0).unwrap(), vec![7; bytes]);
    }
    let good = [(0, 0, vec![1; 8], 8, false), (1, 2, vec![2; 16], 16, false)];
    for (w, h, mips, format) in [
        (0, 4, 3, 71),
        (4, 0, 3, 71),
        (4, 4, 0, 71),
        (4, 4, 4, 71),
        (u16::MAX, u16::MAX, 1, 28),
        (4, 4, 3, 0),
    ] {
        assert!(member_bytes(
            &texture_payload(1, 0, format, w, h, mips, false, &good),
            "a.dds",
            u64::MAX
        )
        .is_err());
    }
    for chunks in [
        vec![good[0].clone(), good[0].clone()],
        vec![good[0].clone()],
        vec![(0, 3, vec![0; 32], 32, false)],
        vec![(0, 2, vec![0; 23], 23, false)],
    ] {
        assert!(member_bytes(
            &texture_payload(1, 0, 71, 4, 4, 3, false, &chunks),
            "a.dds",
            1000
        )
        .is_err());
    }
    let block = lz4_flex::block::compress(&[4; 24]);
    for end in 0..block.len() {
        let b = texture_payload(
            3,
            3,
            71,
            4,
            4,
            3,
            false,
            &[(0, 2, block[..end].to_vec(), 24, true)],
        );
        assert!(member_bytes(&b, "a.dds", 1000).is_err());
    }
    let b = texture_payload(3, 9, 71, 4, 4, 3, false, &good);
    assert!(member_bytes(&b, "a.dds", 1000).is_err());
    let mut b = texture_payload(3, 3, 71, 4, 4, 3, false, &good);
    b[36 + 22] = 2;
    assert!(member_bytes(&b, "a.dds", 1000).is_err());
}

#[test]
fn payload_export_stages_and_preserves_source_and_destination_on_failure() {
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("source.ba2");
    let dest = dir.path().join("chosen.txt");
    let good = general_payload(1, &zlib_bytes(b"hello world"), 11, true);
    std::fs::write(&source, &good).unwrap();
    std::fs::write(&dest, b"original").unwrap();
    assert!(export_archive_member(&source, "a.txt", &dest, 10).is_err());
    assert_eq!(std::fs::read(&dest).unwrap(), b"original");
    let mut bad = zlib_bytes(b"hello world");
    bad.pop();
    std::fs::write(&source, general_payload(1, &bad, 11, true)).unwrap();
    assert!(export_archive_member(&source, "a.txt", &dest, 100).is_err());
    assert_eq!(std::fs::read(&dest).unwrap(), b"original");
    std::fs::write(&source, &good).unwrap();
    let identity = archive_identity(&source).unwrap();
    assert_eq!(
        read_archive_member_checked(&source, "a.txt", 100, Some(&identity)).unwrap(),
        b"hello world"
    );
    let info =
        export_archive_member_checked(&source, "a.txt", &dest, 100, Some(&identity)).unwrap();
    assert_eq!(info.bytes_written, 11);
    assert_eq!(std::fs::read(&dest).unwrap(), b"hello world");
    assert_eq!(std::fs::read(&source).unwrap(), good);
    let fresh = dir.path().join("new.txt");
    export_archive_member(&source, "a.txt", &fresh, 100).unwrap();
    assert_eq!(std::fs::read(&fresh).unwrap(), b"hello world");
    assert_eq!(
        std::fs::read_dir(dir.path()).unwrap().count(),
        3,
        "stages are removed"
    );
}
#[test]
fn payload_export_rejects_source_aliases_symlinks_and_unsafe_paths() {
    use std::os::unix::fs::symlink;
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("source.ba2");
    let good = general_payload(1, b"hello world", 11, false);
    std::fs::write(&source, &good).unwrap();
    let hard = dir.path().join("hard.txt");
    std::fs::hard_link(&source, &hard).unwrap();
    let link = dir.path().join("symlink.txt");
    symlink(&source, &link).unwrap();
    let parent = dir.path().join("linked");
    symlink(dir.path(), &parent).unwrap();
    for dest in [
        source.clone(),
        hard,
        link,
        parent.join("outside.txt"),
        dir.path().join("../outside.txt"),
        dir.path().to_path_buf(),
    ] {
        assert!(
            export_archive_member(&source, "a.txt", &dest, 100).is_err(),
            "{}",
            dest.display()
        );
        assert_eq!(std::fs::read(&source).unwrap(), good);
    }
    let dest = dir.path().join("out.txt");
    for member in [
        "../a.txt",
        "/a.txt",
        "C:/a.txt",
        "a/../a.txt",
        "a\\..\\a.txt",
    ] {
        assert!(export_archive_member(&source, member, &dest, 100).is_err());
        assert!(!dest.exists());
    }
}
#[test]
fn payload_source_identity_rejects_replaced_and_mid_read_changed_archives() {
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("source.ba2");
    std::fs::write(&source, general_payload(1, b"hello world", 11, false)).unwrap();
    let identity = archive_identity(&source).unwrap();
    std::fs::rename(&source, dir.path().join("old.ba2")).unwrap();
    std::fs::write(&source, general_payload(1, b"other bytes", 11, false)).unwrap();
    assert!(read_archive_member_checked(&source, "a.txt", 100, Some(&identity)).is_err());
    let dest = dir.path().join("out.txt");
    std::fs::write(&dest, b"original").unwrap();
    assert!(export_archive_member_checked(&source, "a.txt", &dest, 100, Some(&identity)).is_err());
    assert_eq!(std::fs::read(&dest).unwrap(), b"original");
    struct MutatingWriter<'a>(&'a Path);
    impl Write for MutatingWriter<'_> {
        fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
            std::fs::OpenOptions::new()
                .append(true)
                .open(self.0)?
                .write_all(b"mutation")?;
            Ok(bytes.len())
        }
        fn flush(&mut self) -> io::Result<()> {
            Ok(())
        }
    }
    let mut file = File::open(&source).unwrap();
    assert!(write_archive_member(&mut file, "a.txt", 100, &mut MutatingWriter(&source)).is_err());
}
#[test]
fn payload_tes3_relative_offsets_and_zero_length_members() {
    let name = b"a.txt\0";
    let hash = 24 + name.len();
    let payload = hash + 8;
    let mut b = vec![0; payload + 3];
    put32(&mut b, 0, 0x100);
    put32(&mut b, 4, (hash - 12) as u32);
    put32(&mut b, 8, 1);
    put32(&mut b, 12, 11);
    put32(&mut b, 16, 3);
    b[24..hash].copy_from_slice(name);
    b.extend_from_slice(b"hello world");
    assert_eq!(member_bytes(&b, "A.TXT", 11).unwrap(), b"hello world");
    for version in [1, 2, 3, 7, 8] {
        assert_eq!(
            member_bytes(&general_payload(version, b"", 0, false), "a.txt", 0).unwrap(),
            b""
        );
    }
}

#[test]
fn payload_export_rejects_directory_syntax_instead_of_changing_filename() {
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("source.ba2");
    std::fs::write(&source, general_payload(1, b"hello world", 11, false)).unwrap();
    for suffix in ["new.txt/", "new.txt/.", "."] {
        let dest = dir.path().join(suffix);
        assert!(
            export_archive_member(&source, "a.txt", &dest, 100).is_err(),
            "{}",
            dest.display()
        );
    }
    assert_eq!(std::fs::read_dir(dir.path()).unwrap().count(), 1);
}
#[test]
fn payload_gzip_and_lz4_blocks_require_complete_exact_streams() {
    let mut gzip = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
    gzip.write_all(b"hello world").unwrap();
    let gzip = gzip.finish().unwrap();
    for end in 0..gzip.len() {
        assert!(
            member_bytes(&general_payload(1, &gzip[..end], 11, true), "a.txt", 100).is_err(),
            "gzip truncation {end}"
        );
    }
    let mut bad = gzip.clone();
    *bad.last_mut().unwrap() ^= 1;
    assert!(member_bytes(&general_payload(1, &bad, 11, true), "a.txt", 100).is_err());
    let mut trailing = gzip;
    trailing.push(0);
    assert!(member_bytes(&general_payload(1, &trailing, 11, true), "a.txt", 100).is_err());
    let block = lz4_flex::block::compress(b"hello world");
    let mut b = general_payload(3, &block, 11, true);
    put32(&mut b, 32, 3);
    assert_eq!(member_bytes(&b, "a.txt", 11).unwrap(), b"hello world");
    for declared in [10, 12, u32::MAX] {
        let mut b = general_payload(3, &block, declared, true);
        put32(&mut b, 32, 3);
        assert!(member_bytes(&b, "a.txt", u64::MAX).is_err());
    }
    let mut block = block;
    block.push(0);
    let mut b = general_payload(3, &block, 11, true);
    put32(&mut b, 32, 3);
    assert!(member_bytes(&b, "a.txt", 11).is_err());
}

#[test]
fn payload_lz4_frame_without_checksums_still_requires_end_marker() {
    let mut encoder = lz4_flex::frame::FrameEncoder::new(Vec::new());
    encoder.write_all(b"hello world").unwrap();
    let frame = encoder.finish().unwrap();
    assert_eq!(
        member_bytes(
            &bsa_payload(105, &frame, true, false, false),
            "textures/a.txt",
            11
        )
        .unwrap(),
        b"hello world"
    );
    assert!(member_bytes(
        &bsa_payload(105, &frame[..frame.len() - 4], true, false, false),
        "textures/a.txt",
        11
    )
    .is_err());
}
#[test]
fn payload_lz4_empty_data_block_cannot_replace_the_end_marker() {
    let mut encoder = lz4_flex::frame::FrameEncoder::new(Vec::new());
    encoder.write_all(b"hello world").unwrap();
    let mut frame = encoder.finish().unwrap();
    // 0x80000000 is an empty uncompressed data block, not the zero end marker.
    let end = frame.len() - 4;
    frame[end..].copy_from_slice(&0x80000000u32.to_le_bytes());
    assert!(member_bytes(
        &bsa_payload(105, &frame, true, false, false),
        "textures/a.txt",
        11
    )
    .is_err());
}

#[test]
fn payload_lz4_frame_accepts_empty_blocks_and_rejects_missing_footer() {
    // Handwritten standard frame: independent 64-KiB blocks, no checksums,
    // one raw block, and the required EndMark. Header checksum is 0x82.
    let mut fixed = b"\x04\x22\x4d\x18\x60\x40\x82\x0b\0\0\x80hello world".to_vec();
    fixed.extend_from_slice(&[0; 4]);
    assert_eq!(
        member_bytes(
            &bsa_payload(105, &fixed, true, false, false),
            "textures/a.txt",
            11
        )
        .unwrap(),
        b"hello world"
    );
    for block_checksum in [false, true] {
        for content_checksum in [false, true] {
            let info = lz4_flex::frame::FrameInfo::new()
                .block_checksums(block_checksum)
                .content_checksum(content_checksum)
                .content_size(Some(11));
            let mut encoder = lz4_flex::frame::FrameEncoder::with_frame_info(info, Vec::new());
            encoder.write_all(b"hello world").unwrap();
            let frame = encoder.finish().unwrap();
            let footer = if content_checksum { 8 } else { 4 };
            for at in [15, frame.len() - footer] {
                let mut empty = 0x80000000u32.to_le_bytes().to_vec();
                if block_checksum {
                    // XXH32(empty, seed=0), fixed independently of the encoder.
                    empty.extend_from_slice(&0x02cc5d05u32.to_le_bytes());
                }
                let mut bytes = frame.clone();
                bytes.splice(at..at, empty);
                assert_eq!(
                    member_bytes(
                        &bsa_payload(105, &bytes, true, false, false),
                        "textures/a.txt",
                        11
                    )
                    .unwrap(),
                    b"hello world"
                );
                bytes.truncate(bytes.len() - footer);
                assert!(member_bytes(
                    &bsa_payload(105, &bytes, true, false, false),
                    "textures/a.txt",
                    11
                )
                .is_err());
            }
        }
    }
}

#[test]
fn payload_streams_cross_buffer_and_linked_frame_block_boundaries() {
    let expected: Vec<_> = (0..196_609).map(|i| (i % 251) as u8).collect();
    let general = general_payload(1, &zlib_bytes(&expected), expected.len() as u32, true);
    assert_eq!(
        member_bytes(&general, "a.txt", expected.len() as u64).unwrap(),
        expected
    );
    for mode in [
        lz4_flex::frame::BlockMode::Independent,
        lz4_flex::frame::BlockMode::Linked,
    ] {
        let info = lz4_flex::frame::FrameInfo::new()
            .block_size(lz4_flex::frame::BlockSize::Max64KB)
            .block_mode(mode)
            .block_checksums(true)
            .content_checksum(true);
        let mut encoder = lz4_flex::frame::FrameEncoder::with_frame_info(info, Vec::new());
        encoder.write_all(&expected).unwrap();
        let mut b = bsa_payload(105, &encoder.finish().unwrap(), true, false, false);
        let record = 60 + 1 + b[60] as usize;
        let offset = u32_at(&b, record + 12) as usize;
        put32(&mut b, offset, expected.len() as u32);
        assert_eq!(
            member_bytes(&b, "textures/a.txt", expected.len() as u64).unwrap(),
            expected
        );
        put32(&mut b, offset, 11);
        assert!(member_bytes(&b, "textures/a.txt", 11).is_err());
    }
}

#[test]
fn payload_bsa_combined_name_obeys_the_shared_path_bound() {
    let accepted = format!("textures/{}", "a".repeat(MAX_PATH - 9));
    let rejected = format!("textures/{}", "a".repeat(MAX_PATH - 8));
    for version in [103, 104, 105] {
        assert_eq!(
            member_bytes(&bsa_fixture(version, &accepted), &accepted, 1).unwrap(),
            [0]
        );
        assert!(read_members(Cursor::new(bsa_fixture(version, &rejected))).is_err());
    }
}

#[test]
fn payload_rejects_nonregular_sources_embedded_path_overruns_and_sink_failures() {
    let dir = tempfile::tempdir().unwrap();
    let fifo = dir.path().join("source.bsa");
    rustix::fs::mknodat(
        rustix::fs::CWD,
        &fifo,
        rustix::fs::FileType::Fifo,
        rustix::fs::Mode::RUSR | rustix::fs::Mode::WUSR,
        0,
    )
    .unwrap();
    assert!(archive_identity(&fifo).is_err());
    assert!(archive_identity(dir.path()).is_err());
    for version in [103, 104, 105] {
        let mut b = bsa_payload(version, b"hello world", false, false, true);
        let header = if version == 105 { 60 } else { 52 };
        let record = header + 1 + b[header] as usize;
        let offset = u32_at(&b, record + 12) as usize;
        b[offset] = 255;
        assert!(member_bytes(&b, "textures/a.txt", 100).is_err());
        b[offset] = 14;
        b[offset + 1..offset + 4].copy_from_slice(b"../");
        assert!(member_bytes(&b, "textures/a.txt", 100).is_err());
    }
    struct FailingWriter;
    impl Write for FailingWriter {
        fn write(&mut self, _: &[u8]) -> io::Result<usize> {
            Err(io::Error::other("synthetic sink failure"))
        }
        fn flush(&mut self) -> io::Result<()> {
            Ok(())
        }
    }
    let mut file = tempfile::tempfile().unwrap();
    file.write_all(&general_payload(1, b"hello world", 11, false))
        .unwrap();
    assert!(matches!(
        write_archive_member(&mut file, "a.txt", 11, &mut FailingWriter),
        Err(ArchiveError::Io(_))
    ));
}
#[test]
fn payload_duplicate_names_fail_without_writing_a_prefix() {
    let mut b = vec![0; 96];
    b[..4].copy_from_slice(b"BTDX");
    b[8..12].copy_from_slice(b"GNRL");
    put32(&mut b, 4, 1);
    put32(&mut b, 12, 2);
    put64(&mut b, 16, 107);
    for rec in [24, 60] {
        put64(&mut b, rec + 16, 96);
        put32(&mut b, rec + 28, 11);
    }
    b.extend_from_slice(b"hello world\x05\0a.txt\x05\0A.TXT");
    let mut file = tempfile::tempfile().unwrap();
    file.write_all(&b).unwrap();
    let mut output = Vec::new();
    assert!(write_archive_member(&mut file, "a.txt", 100, &mut output).is_err());
    assert!(output.is_empty());
}
